export const Data = [
  {
    user: "Tibau",
    total_wins: 4,
    kills: 4,
    deaths: 25,
    assists: 8,
    flashbang_assists: 0,
    total_rounds_played: 32,
    rating: 0.4,
  },
  {
    user: "Jamal em outra semana",
    total_wins: 7,
    kills: 20,
    deaths: 15,
    assists: 2,
    flashbang_assists: 3,
    total_rounds_played: 32,
    rating: 1.4,
  },
  {
    user: "Vioto",
    total_wins: 5,
    kills: 15,
    deaths: 15,
    assists: 6,
    flashbang_assists: 2,
    total_rounds_played: 32,
    rating: 1.0,
  },
  {
    user: "1Brust",
    total_wins: 5,
    kills: 20,
    deaths: 18,
    assists: 5,
    flashbang_assists: 5,
    total_rounds_played: 32,
    rating: 1.2,
  },
];
